version: '3.8'

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./app:/app
    command: uvicorn main:create_app --factory --host=0.0.0.0 --port=8080 --reload
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - 5432:5432
